<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-09 at 17:02:41.
 */
class LivroTest extends PHPUnit_Framework_TestCase {

    protected $livro;
    
    protected function setUp() {
        $this->livro = new LivroControlador;
    }

    protected function tearDown() {
        
    }

    public function testSetTitulo() {
        
    }
    
    public function testSetAutor() {
        
    }
    
    public function testDefineTiposDeGeneros() {
        
    }

    public function testSetEditora() {
       
    }


}
